# Generated by Django 3.2 on 2022-10-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modeldetailedresult",
            name="v",
            field=models.FloatField(verbose_name="计算体积"),
        ),
    ]
