# Generated by Django 3.2 on 2022-10-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0002_alter_modeldetailedresult_v"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeldetailedresult",
            name="construction_detailed",
            field=models.TextField(
                blank=True, null=True, verbose_name="construction_detailed"
            ),
        ),
    ]
