# Generated by Django 3.2 on 2023-03-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0004_rebarlayoutmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detaildata",
            name="demold_type",
            field=models.IntegerField(
                choices=[(0, "ROUNDING_HEAD"), (1, "ANCHOR")],
                default=1,
                verbose_name="脱模类型",
            ),
        ),
        migrations.AlterField(
            model_name="modeldetailedresult",
            name="demold_type",
            field=models.IntegerField(
                choices=[(0, "ROUNDING_HEAD"), (1, "ANCHOR")],
                default=0,
                verbose_name="吊装预埋件类型",
            ),
        ),
    ]
