# Generated by Django 3.2 on 2023-03-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0005_auto_20230316_1512"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconstructiondata",
            name="component_num",
            field=models.CharField(
                blank=True,
                help_text="下层结构计算需要该参数",
                max_length=64,
                null=True,
                verbose_name="构件编号",
            ),
        ),
        migrations.AddField(
            model_name="modelconstructiondata",
            name="project_num",
            field=models.CharField(
                blank=True,
                help_text="下层结构计算需要该参数",
                max_length=64,
                null=True,
                verbose_name="项目编号",
            ),
        ),
    ]
