# Generated by Django 3.2 on 2023-03-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0006_auto_20230317_1012"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconstructionresult",
            name="ksi_b",
            field=models.FloatField(blank=True, help_text="对应下层变动", null=True),
        ),
    ]
