# Generated by Django 3.2 on 2023-03-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0007_modelconstructionresult_ksi_b"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelconstructionresult",
            name="ksi_b",
            field=models.FloatField(
                blank=True, help_text="对应下层变动", null=True, verbose_name="界限相对受压区高度变换系数"
            ),
        ),
    ]
