# Generated by Django 3.2 on 2023-03-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0008_alter_modelconstructionresult_ksi_b"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detaildata",
            name="rail_design_mode",
            field=models.IntegerField(
                choices=[(1, "手动"), (2, "不计算")],
                default=1,
                verbose_name="rail_design_mode",
            ),
        ),
    ]
