# Generated by Django 3.2 on 2023-03-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0009_alter_detaildata_rail_design_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modeldetailedresult",
            name="rail_parameter_a",
            field=models.IntegerField(blank=True, null=True, verbose_name="a"),
        ),
        migrations.AlterField(
            model_name="modeldetailedresult",
            name="rail_parameter_b",
            field=models.IntegerField(blank=True, null=True, verbose_name="b"),
        ),
        migrations.AlterField(
            model_name="modeldetailedresult",
            name="rail_parameter_c",
            field=models.IntegerField(blank=True, null=True, verbose_name="c"),
        ),
        migrations.AlterField(
            model_name="modeldetailedresult",
            name="rail_parameter_d",
            field=models.IntegerField(blank=True, null=True, verbose_name="d"),
        ),
        migrations.AlterField(
            model_name="modeldetailedresult",
            name="rail_parameter_depth",
            field=models.IntegerField(blank=True, null=True, verbose_name="栏杆埋入深度"),
        ),
        migrations.AlterField(
            model_name="modeldetailedresult",
            name="rail_parameter_fi",
            field=models.IntegerField(blank=True, null=True, verbose_name="直径"),
        ),
        migrations.AlterField(
            model_name="modeldetailedresult",
            name="rail_parameter_length",
            field=models.IntegerField(blank=True, null=True, verbose_name="底边长度"),
        ),
        migrations.AlterField(
            model_name="modeldetailedresult",
            name="rail_parameter_t",
            field=models.IntegerField(blank=True, null=True, verbose_name="t"),
        ),
    ]
