# Generated by Django 3.2 on 2023-03-29 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0010_auto_20230324_0753"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detaildata",
            name="bottom_fix_hinge_c1",
        ),
        migrations.RemoveField(
            model_name="detaildata",
            name="bottom_fix_hinge_d1",
        ),
        migrations.RemoveField(
            model_name="detaildata",
            name="bottom_fix_hinge_e1",
        ),
        migrations.RemoveField(
            model_name="detaildata",
            name="bottom_fix_hinge_f1",
        ),
        migrations.RemoveField(
            model_name="detaildata",
            name="bottom_fix_hinge_h1",
        ),
        migrations.RemoveField(
            model_name="detaildata",
            name="bottom_sliding_hinge_c2",
        ),
        migrations.RemoveField(
            model_name="detaildata",
            name="bottom_sliding_hinge_d2",
        ),
        migrations.RemoveField(
            model_name="detaildata",
            name="top_fix_hinge_c1",
        ),
        migrations.RemoveField(
            model_name="detaildata",
            name="top_fix_hinge_d1",
        ),
        migrations.RemoveField(
            model_name="detaildata",
            name="top_fix_hinge_e1",
        ),
        migrations.RemoveField(
            model_name="detaildata",
            name="top_fix_hinge_f1",
        ),
        migrations.RemoveField(
            model_name="detaildata",
            name="top_fix_hinge_h1",
        ),
        migrations.RemoveField(
            model_name="detaildata",
            name="top_sliding_hinge_c2",
        ),
        migrations.RemoveField(
            model_name="detaildata",
            name="top_sliding_hinge_d2",
        ),
    ]
