# Generated by Django 3.2 on 2023-03-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0011_auto_20230329_0813"),
    ]

    operations = [
        migrations.AddField(
            model_name="detaildata",
            name="bottom_fix_hinge_c2",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="fix_hinge_c2"
            ),
        ),
        migrations.AddField(
            model_name="detaildata",
            name="bottom_fix_hinge_d2",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="fix_hinge_d2"
            ),
        ),
        migrations.AddField(
            model_name="detaildata",
            name="bottom_sliding_hinge_c1",
            field=models.IntegerField(blank=True, null=True, verbose_name="hinge_c1"),
        ),
        migrations.AddField(
            model_name="detaildata",
            name="bottom_sliding_hinge_d1",
            field=models.IntegerField(blank=True, null=True, verbose_name="hinge_d1"),
        ),
        migrations.AddField(
            model_name="detaildata",
            name="bottom_sliding_hinge_e1",
            field=models.IntegerField(blank=True, null=True, verbose_name="hinge_e1"),
        ),
        migrations.AddField(
            model_name="detaildata",
            name="bottom_sliding_hinge_f1",
            field=models.IntegerField(blank=True, null=True, verbose_name="hinge_f1"),
        ),
        migrations.AddField(
            model_name="detaildata",
            name="bottom_sliding_hinge_h1",
            field=models.IntegerField(blank=True, null=True, verbose_name="hinge_h1"),
        ),
        migrations.AddField(
            model_name="detaildata",
            name="top_fix_hinge_c2",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="fix_hinge_c2"
            ),
        ),
        migrations.AddField(
            model_name="detaildata",
            name="top_fix_hinge_d2",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="fix_hinge_d2"
            ),
        ),
        migrations.AddField(
            model_name="detaildata",
            name="top_sliding_hinge_c1",
            field=models.IntegerField(blank=True, null=True, verbose_name="hinge_c1"),
        ),
        migrations.AddField(
            model_name="detaildata",
            name="top_sliding_hinge_d1",
            field=models.IntegerField(blank=True, null=True, verbose_name="hinge_d1"),
        ),
        migrations.AddField(
            model_name="detaildata",
            name="top_sliding_hinge_e1",
            field=models.IntegerField(blank=True, null=True, verbose_name="hinge_e1"),
        ),
        migrations.AddField(
            model_name="detaildata",
            name="top_sliding_hinge_f1",
            field=models.IntegerField(blank=True, null=True, verbose_name="hinge_f1"),
        ),
        migrations.AddField(
            model_name="detaildata",
            name="top_sliding_hinge_h1",
            field=models.IntegerField(blank=True, null=True, verbose_name="hinge_h1"),
        ),
    ]
