# Generated by Django 3.2 on 2023-03-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0012_auto_20230329_0817"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailDataCopyChangeWrite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField(verbose_name="design parameter")),
            ],
            options={
                "verbose_name": "深化设计参数修改",
                "verbose_name_plural": "深化设计参数修改",
            },
        ),
    ]
