# Generated by Django 3.2 on 2023-03-29 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0013_detaildatacopychangewrite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detaildatacopychangewrite",
            options={"verbose_name": "深化设计-参数修改", "verbose_name_plural": "深化设计-参数修改"},
        ),
        migrations.AddField(
            model_name="modeldetailedresult",
            name="detailed_design",
            field=models.ForeignKey(
                help_text="针对stair-detailed 1.0.0 所作改动,仅存储,但不做展示",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="design.detaildatacopychangewrite",
                verbose_name="参数修改",
            ),
        ),
    ]
