# Generated by Django 3.2 on 2023-03-31 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0015_alter_rebarlayoutmodel_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ifc",
                    models.FileField(upload_to="%Y/%m/%d", verbose_name="IFC 模型文件"),
                ),
                (
                    "stair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="design.modelconstructiondata",
                        verbose_name="导出文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "楼梯导出模型",
                "verbose_name_plural": "楼梯导出模型",
            },
        ),
    ]
