# Generated by Django 3.2 on 2023-04-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0016_fileexport"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileexport",
            name="bvbs",
            field=models.FileField(
                null=True, upload_to="%Y/%m/%d", verbose_name="BVBS"
            ),
        ),
        migrations.AddField(
            model_name="fileexport",
            name="zip_json",
            field=models.FileField(
                null=True, upload_to="%Y/%m/%d", verbose_name="Rebar Json Zip"
            ),
        ),
        migrations.AlterField(
            model_name="fileexport",
            name="ifc",
            field=models.FileField(
                null=True, upload_to="%Y/%m/%d", verbose_name="IFC 模型文件"
            ),
        ),
    ]
