# Generated by Django 3.2 on 2023-04-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0017_auto_20230410_1212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="component_num",
            field=models.CharField(
                blank=True,
                default="",
                help_text="下层结构计算需要该参数",
                max_length=64,
                null=True,
                verbose_name="构件编号",
            ),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="project_num",
            field=models.CharField(
                blank=True,
                default="",
                help_text="下层结构计算需要该参数",
                max_length=64,
                null=True,
                verbose_name="项目编号",
            ),
        ),
    ]
