# Generated by Django 3.2 on 2023-12-19 08:49

import design.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0020_auto_20230418_1150"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="bottom_top_length",
            field=models.IntegerField(null=True, verbose_name="底端上边长 Lb(mm)"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="clear_span",
            field=models.IntegerField(null=True, verbose_name="净跨 Ln(mm)"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="crack",
            field=models.FloatField(null=True, verbose_name="裂缝限值wmax(mm)"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="height",
            field=models.IntegerField(null=True, verbose_name="楼梯高度 H(mm)"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="live_load",
            field=models.FloatField(null=True, verbose_name="可变荷载 qqk(kN/m^2)"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="live_load_load_partial_factor",
            field=models.FloatField(null=True, verbose_name="可变荷载分项系数 rQ"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="longitudinal_top_stress_bar_margin",
            field=models.IntegerField(default=20, verbose_name="纵筋合力点边距 as(mm)"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="permanent_load_partial_factor",
            field=models.FloatField(null=True, verbose_name="永久荷载分项系数 rG"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="protective_layer_thickness",
            field=models.IntegerField(default=20, verbose_name="保护层厚度 c(mm)"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="quasi_permanent_value_coefficient",
            field=models.FloatField(null=True, verbose_name="准永久值系数 ψq"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="railing_load",
            field=models.FloatField(null=True, verbose_name="栏杆荷载 gf(kN/m)"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="reinforced_concrete_bulk_density",
            field=models.FloatField(null=True, verbose_name="钢筋混凝土容重 Rc(kN/m^3)"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="remark_name",
            field=models.CharField(
                default=design.models.get_default_remark_name,
                max_length=64,
                null=True,
                verbose_name="参数编号",
            ),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="thickness",
            field=models.IntegerField(null=True, verbose_name="梯段板厚度 t(mm)"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="top_top_length",
            field=models.IntegerField(null=True, verbose_name="顶端上边长 Lt(mm)"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="weight",
            field=models.IntegerField(null=True, verbose_name="梯段板宽度 B0(mm)"),
        ),
    ]
