# Generated by Django 3.2 on 2023-12-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0021_auto_20231219_1649"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_b",
            field=models.IntegerField(default=0, verbose_name="底端挑耳宽度 b2(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_edge_longitudinal_rebar_diameter",
            field=models.IntegerField(blank=True, null=True, verbose_name="直径D mm"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_edge_longitudinal_rebar_spacing",
            field=models.IntegerField(blank=True, null=True, verbose_name="间距S mm"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_edge_reinforce_rebar_diameter",
            field=models.IntegerField(blank=True, null=True, verbose_name="直径D mm"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_edge_stirrup_diameter",
            field=models.IntegerField(blank=True, null=True, verbose_name="直径D mm"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_edge_stirrup_spacing",
            field=models.IntegerField(blank=True, null=True, verbose_name="间距S mm"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_fix_hinge_c2",
            field=models.IntegerField(blank=True, null=True, verbose_name=" c2(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_fix_hinge_d2",
            field=models.IntegerField(blank=True, null=True, verbose_name=" d2(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_hole_position_a1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" b1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_hole_position_a2",
            field=models.IntegerField(blank=True, null=True, verbose_name=" b2(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_hole_position_b1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" b3(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_hole_position_b2",
            field=models.IntegerField(blank=True, null=True, verbose_name=" b4(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_joint_a",
            field=models.IntegerField(blank=True, null=True, verbose_name=" a(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_joint_b",
            field=models.IntegerField(blank=True, null=True, verbose_name=" b(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_joint_c",
            field=models.IntegerField(blank=True, null=True, verbose_name=" c(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_sliding_hinge_c1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" c1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_sliding_hinge_d1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" d1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_sliding_hinge_e1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" e1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_sliding_hinge_f1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" f1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_sliding_hinge_h1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" h1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_thickness",
            field=models.IntegerField(default=200, verbose_name="底端板厚 h2(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_top_length",
            field=models.IntegerField(default=400, verbose_name="底端上边长 Lb(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="demold_design_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")], default=0, verbose_name="脱模预埋件设计方式"
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="demold_position_a",
            field=models.IntegerField(blank=True, null=True, verbose_name=" a(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="demold_position_b",
            field=models.IntegerField(blank=True, null=True, verbose_name=" b(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="demold_position_c",
            field=models.IntegerField(blank=True, null=True, verbose_name=" c(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="demold_position_d",
            field=models.IntegerField(blank=True, null=True, verbose_name=" d(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="demold_position_t",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="预埋件侧面位置参数 t(mm)"
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="demold_type",
            field=models.IntegerField(
                choices=[(0, "圆头吊钉"), (1, "锚栓")], default=1, verbose_name="脱模预埋件类型"
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="hoist_design_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")], default=1, verbose_name="吊装预埋件设计方式"
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="hoist_position_a",
            field=models.IntegerField(blank=True, null=True, verbose_name=" a(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="hoist_position_b",
            field=models.IntegerField(blank=True, null=True, verbose_name=" b(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="hoist_position_c",
            field=models.FloatField(blank=True, null=True, verbose_name=" c(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="hoist_position_d",
            field=models.FloatField(blank=True, null=True, verbose_name=" d(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="hoisting_reinforce_rebar_diameter",
            field=models.IntegerField(blank=True, null=True, verbose_name="直径D mm"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="hole_design_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")], default=0, verbose_name="孔洞设计方式"
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="hole_reinforce_rebar_diameter",
            field=models.IntegerField(blank=True, null=True, verbose_name="直径D mm"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="joint_design_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")], default=1, verbose_name="节点设计方式"
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="rail_design_mode",
            field=models.IntegerField(
                choices=[(1, "手动"), (2, "不计算")], default=1, verbose_name="栏杆预埋件设计方式"
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="rail_name",
            field=models.CharField(
                default="M1", max_length=64, null=True, verbose_name="栏杆预埋件型号"
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="rail_position_a",
            field=models.FloatField(blank=True, null=True, verbose_name=" a(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="rail_position_b",
            field=models.FloatField(blank=True, null=True, verbose_name=" b(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="step_slot_a",
            field=models.IntegerField(blank=True, null=True, verbose_name=" a(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="step_slot_b",
            field=models.IntegerField(blank=True, null=True, verbose_name=" b(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="step_slot_c",
            field=models.IntegerField(blank=True, null=True, verbose_name=" c(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="step_slot_d",
            field=models.IntegerField(blank=True, null=True, verbose_name=" d(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="step_slot_design_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")], default=1, verbose_name="防滑槽设计方式"
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="step_slot_e",
            field=models.IntegerField(blank=True, null=True, verbose_name=" e(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="step_slot_position_c1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" c1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="step_slot_position_c2",
            field=models.IntegerField(blank=True, null=True, verbose_name=" c2(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="step_slot_position_c3",
            field=models.IntegerField(blank=True, null=True, verbose_name=" c3(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_b",
            field=models.IntegerField(default=80, verbose_name="顶端挑耳宽度 b1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_edge_longitudinal_rebar_diameter",
            field=models.IntegerField(blank=True, null=True, verbose_name="直径D mm"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_edge_longitudinal_rebar_spacing",
            field=models.IntegerField(blank=True, null=True, verbose_name="间距S mm"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_edge_reinforce_rebar_diameter",
            field=models.IntegerField(blank=True, null=True, verbose_name="直径D mm"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_edge_stirrup_diameter",
            field=models.IntegerField(blank=True, null=True, verbose_name="直径D mm"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_edge_stirrup_spacing",
            field=models.IntegerField(blank=True, null=True, verbose_name="间距S mm"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_fix_hinge_c2",
            field=models.IntegerField(blank=True, null=True, verbose_name=" c2(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_fix_hinge_d2",
            field=models.IntegerField(blank=True, null=True, verbose_name=" d2(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_hole_position_a1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" a1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_hole_position_a2",
            field=models.IntegerField(blank=True, null=True, verbose_name=" a2(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_hole_position_b1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" a3(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_hole_position_b2",
            field=models.IntegerField(blank=True, null=True, verbose_name=" a4(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_joint_a",
            field=models.IntegerField(blank=True, null=True, verbose_name=" a(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_joint_b",
            field=models.IntegerField(blank=True, null=True, verbose_name=" b(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_joint_c",
            field=models.IntegerField(blank=True, null=True, verbose_name=" c(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_sliding_hinge_c1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" c1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_sliding_hinge_d1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" d1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_sliding_hinge_e1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" e1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_sliding_hinge_f1",
            field=models.IntegerField(blank=True, null=True, verbose_name=" f1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_thickness",
            field=models.IntegerField(default=200, verbose_name="顶端板厚 h1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_to_length",
            field=models.IntegerField(default=400, verbose_name="顶端上边长 Lt(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_design_mode",
            field=models.IntegerField(
                choices=[(1, "手动"), (2, "No")], default=1, verbose_name="滴水槽设计方式"
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_layout",
            field=models.IntegerField(
                choices=[(0, "只顶端"), (1, "只底端"), (2, "顶端和底端")],
                default=2,
                verbose_name="滴水槽设计方式",
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_position_a1",
            field=models.FloatField(blank=True, null=True, verbose_name=" a1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_position_a2",
            field=models.FloatField(blank=True, null=True, verbose_name=" a2(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_position_a3",
            field=models.FloatField(blank=True, null=True, verbose_name=" a3(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_semicircle_a",
            field=models.FloatField(blank=True, null=True, verbose_name=" a(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_semicircle_b",
            field=models.FloatField(blank=True, null=True, verbose_name=" b(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_shape",
            field=models.IntegerField(
                choices=[(1, "半圆"), (0, "梯形")], default=0, verbose_name="滴水槽截面类型"
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_trapezoid_a",
            field=models.FloatField(blank=True, null=True, verbose_name=" a(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_trapezoid_b",
            field=models.FloatField(blank=True, null=True, verbose_name=" b(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_trapezoid_c",
            field=models.FloatField(blank=True, null=True, verbose_name=" c(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="width",
            field=models.IntegerField(default=1270, verbose_name="梯段板宽度 B0(mm)"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="crack",
            field=models.FloatField(null=True, verbose_name="裂缝限制 mm"),
        ),
        migrations.AlterField(
            model_name="modeldetailedresult",
            name="demold_type",
            field=models.IntegerField(
                choices=[(0, "圆头吊钉"), (1, "锚栓")], default=0, verbose_name="吊装预埋件类型"
            ),
        ),
    ]
