# Generated by Django 3.2 on 2023-12-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0022_auto_20231221_0802"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detaildata",
            name="hoist_type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "锚栓"), (0, "圆头吊钉")],
                default=0,
                null=True,
                verbose_name="吊装预埋件类型",
            ),
        ),
        migrations.AlterField(
            model_name="modeldetailedresult",
            name="hoist_type",
            field=models.IntegerField(
                choices=[(1, "锚栓"), (0, "圆头吊钉")], default=1, verbose_name="吊装预埋件类型"
            ),
        ),
    ]
