# Generated by Django 4.2.10 on 2024-08-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0024_alter_detaildata_hoist_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detaildata",
            name="pouring_way",
            field=models.IntegerField(
                choices=[
                    (0, "立式浇筑卧式脱模"),
                    (1, "立式浇筑立式脱模"),
                    (2, "卧式浇筑卧式脱模"),
                ],
                default=0,
                verbose_name="脱模方式",
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="rebar_design_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")],
                default=0,
                verbose_name="钢筋设计方式",
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_layout",
            field=models.IntegerField(
                choices=[(0, "只上侧"), (1, "只下侧"), (2, "上侧和下侧")],
                default=2,
                verbose_name="滴水槽设计方式",
            ),
        ),
        migrations.AlterField(
            model_name="modeldetailedresult",
            name="pouring_way",
            field=models.IntegerField(
                choices=[
                    (0, "立式浇筑卧式脱模"),
                    (1, "立式浇筑立式脱模"),
                    (2, "卧式浇筑卧式脱模"),
                ],
                default=0,
                verbose_name="浇筑形式",
            ),
        ),
    ]
