# Generated by Django 4.2.16 on 2024-09-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0025_alter_detaildata_pouring_way_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detaildata",
            name="hoist_design_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")],
                default=0,
                verbose_name="吊装预埋件设计方式",
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="joint_design_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")],
                default=0,
                verbose_name="节点设计方式",
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="rail_design_mode",
            field=models.IntegerField(
                choices=[(1, "手动"), (2, "不计算")],
                default=2,
                verbose_name="栏杆预埋件设计方式",
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="rail_number",
            field=models.TextField(
                blank=True,
                default="3",
                null=True,
                verbose_name="栏杆预埋件所在的阶数",
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="step_slot_design_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")],
                default=0,
                verbose_name="防滑槽设计方式",
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_design_mode",
            field=models.IntegerField(
                choices=[(1, "手动"), (2, "No")],
                default=2,
                verbose_name="滴水槽设计方式",
            ),
        ),
    ]
