# Generated by Django 4.2.16 on 2024-09-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0026_alter_detaildata_hoist_design_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="combined_value_coefficient",
            field=models.FloatField(
                default=0.7, null=True, verbose_name="组合值系数"
            ),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="crack",
            field=models.FloatField(null=True, verbose_name="裂缝限制 (mm)"),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="live_load",
            field=models.FloatField(
                default=3.5, null=True, verbose_name="可变荷载 qqk(kN / m^2)"
            ),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="live_load_load_partial_factor",
            field=models.FloatField(
                default=1.4, null=True, verbose_name="可变荷载分项系数 rQ"
            ),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="permanent_load_partial_factor",
            field=models.FloatField(
                default=1.2, null=True, verbose_name="永久荷载分项系数 rG"
            ),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="quasi_permanent_value_coefficient",
            field=models.FloatField(
                default=0.4, null=True, verbose_name="准永久值系数 ψq"
            ),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="reinforced_concrete_bulk_density",
            field=models.FloatField(
                default=25.0,
                null=True,
                verbose_name="钢筋混凝土容重 Rc(kN / m^2)",
            ),
        ),
    ]
