# Generated by Django 4.2.16 on 2024-09-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "design",
            "0027_alter_modelconstructiondata_combined_value_coefficient_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_thickness",
            field=models.IntegerField(verbose_name="底端板厚 h2(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="bottom_top_length",
            field=models.IntegerField(
                help_text="此参数需和结构设计端保持一致",
                verbose_name="底端上边长 Lb(mm)",
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_b",
            field=models.IntegerField(
                default=0, verbose_name="顶端挑耳宽度 b1(mm)"
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_thickness",
            field=models.IntegerField(verbose_name="顶端板厚 h1(mm)"),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="top_to_length",
            field=models.IntegerField(
                help_text="此参数需和结构设计端保持一致",
                verbose_name="顶端上边长 Lt(mm)",
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="water_drip_layout",
            field=models.IntegerField(
                choices=[(0, "只上侧"), (1, "只下侧"), (2, "上侧和下侧")],
                default=2,
                verbose_name="滴水槽布局方式",
            ),
        ),
        migrations.AlterField(
            model_name="detaildata",
            name="width",
            field=models.IntegerField(
                help_text="此参数需和结构设计端保持一致",
                verbose_name="梯段板宽度 B0(mm)",
            ),
        ),
    ]
