# Generated by Django 4.2.16 on 2024-09-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0028_alter_detaildata_bottom_thickness_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detaildata",
            old_name="top_to_length",
            new_name="top_top_length",
        ),
    ]
