# Generated by Django 4.2.16 on 2024-09-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0029_rename_top_to_length_detaildata_top_top_length"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detaildata",
            old_name="top_top_length",
            new_name="top_to_length",
        ),
    ]
