# Generated by Django 4.2.16 on 2024-09-20 03:05

import design.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0030_rename_top_top_length_detaildata_top_to_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreSetModelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_num",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="下层结构计算需要该参数",
                        max_length=64,
                        null=True,
                        verbose_name="项目编号",
                    ),
                ),
                (
                    "component_num",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="下层结构计算需要该参数",
                        max_length=64,
                        null=True,
                        verbose_name="构件编号",
                    ),
                ),
                (
                    "remark_name",
                    models.CharField(
                        default=design.models.get_default_remark_name,
                        max_length=64,
                        null=True,
                        verbose_name="参数编号",
                    ),
                ),
                (
                    "rebar_name",
                    models.CharField(
                        choices=[
                            ["HPB300", "HPB300"],
                            ["HRB335", "HRB335"],
                            ["HRBF335", "HRBF335"],
                            ["HRB400", "HRB400"],
                            ["HRBF400", "HRBF400"],
                            ["RRB400", "RRB400"],
                            ["HRB500", "HRB500"],
                            ["HRBF500", "HRBF500"],
                        ],
                        default="HPB300",
                        max_length=32,
                        verbose_name="钢筋等级",
                    ),
                ),
                (
                    "concrete_grade",
                    models.IntegerField(
                        choices=[
                            [30, "C30"],
                            [35, "C35"],
                            [40, "C40"],
                            [45, "C45"],
                            [50, "C50"],
                        ],
                        default=30,
                        verbose_name="混凝土等级",
                    ),
                ),
                (
                    "protective_layer_thickness",
                    models.IntegerField(
                        default=20, verbose_name="保护层厚度 c(mm)"
                    ),
                ),
                (
                    "longitudinal_top_stress_bar_margin",
                    models.IntegerField(
                        default=20, verbose_name="纵筋合力点边距 as(mm)"
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        null=True, verbose_name="楼梯高度 H(mm)"
                    ),
                ),
                (
                    "thickness",
                    models.IntegerField(
                        null=True, verbose_name="梯段板厚度 t(mm)"
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        null=True, verbose_name="梯段板宽度 B0(mm)"
                    ),
                ),
                (
                    "clear_span",
                    models.IntegerField(null=True, verbose_name="净跨 Ln(mm)"),
                ),
                (
                    "top_top_length",
                    models.IntegerField(
                        null=True, verbose_name="顶端上边长 Lt(mm)"
                    ),
                ),
                (
                    "bottom_top_length",
                    models.IntegerField(
                        null=True, verbose_name="底端上边长 Lb(mm)"
                    ),
                ),
                (
                    "steps_number",
                    models.IntegerField(null=True, verbose_name="踏步数 N"),
                ),
                (
                    "live_load",
                    models.FloatField(
                        default=3.5,
                        null=True,
                        verbose_name="可变荷载 qqk(kN / m^2)",
                    ),
                ),
                (
                    "railing_load",
                    models.FloatField(
                        null=True, verbose_name="栏杆荷载 gf(kN/m)"
                    ),
                ),
                (
                    "permanent_load_partial_factor",
                    models.FloatField(
                        default=1.2,
                        null=True,
                        verbose_name="永久荷载分项系数 rG",
                    ),
                ),
                (
                    "live_load_load_partial_factor",
                    models.FloatField(
                        default=1.4,
                        null=True,
                        verbose_name="可变荷载分项系数 rQ",
                    ),
                ),
                (
                    "quasi_permanent_value_coefficient",
                    models.FloatField(
                        default=0.4, null=True, verbose_name="准永久值系数 ψq"
                    ),
                ),
                (
                    "combined_value_coefficient",
                    models.FloatField(
                        default=0.7, null=True, verbose_name="组合值系数"
                    ),
                ),
                (
                    "reinforced_concrete_bulk_density",
                    models.FloatField(
                        default=25.0,
                        null=True,
                        verbose_name="钢筋混凝土容重 Rc(kN / m^2)",
                    ),
                ),
                (
                    "crack",
                    models.FloatField(null=True, verbose_name="裂缝限制 (mm)"),
                ),
            ],
            options={
                "verbose_name": "预设模型参数",
                "verbose_name_plural": "预设模型参数",
            },
        ),
    ]
