# Generated by Django 4.2.16 on 2024-09-20 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0032_modelconstructiondata_pre_stair"),
    ]

    operations = [
        migrations.AddField(
            model_name="presetmodeldata",
            name="bottom_b",
            field=models.IntegerField(
                default=0, verbose_name="底端挑耳宽度 b2(mm)"
            ),
        ),
        migrations.AddField(
            model_name="presetmodeldata",
            name="bottom_thickness",
            field=models.IntegerField(
                default=0, verbose_name="底端板厚 h2(mm)"
            ),
        ),
        migrations.AddField(
            model_name="presetmodeldata",
            name="top_b",
            field=models.IntegerField(
                default=0, verbose_name="顶端挑耳宽度 b1(mm)"
            ),
        ),
        migrations.AddField(
            model_name="presetmodeldata",
            name="top_thickness",
            field=models.IntegerField(
                default=0, verbose_name="顶端板厚 h1(mm)"
            ),
        ),
        migrations.AlterField(
            model_name="modelconstructiondata",
            name="pre_stair",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="design.presetmodeldata",
                verbose_name="预设参数",
            ),
        ),
    ]
