# Generated by Django 4.2.16 on 2024-09-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0033_presetmodeldata_bottom_b_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="presetmodeldata",
            old_name="weight",
            new_name="width",
        ),
    ]
