"""
Date&Time           2022/8/3 16:00
Author              Chengran Xu

"""

ROUNDING_HEAD = {
    "DJ-13-120": {
        "type": "圆头吊钉",
        "factory": "现代营造",
        "name": "DJ-13-120",
        "abbreviation": "DJ",
        "capacity": 1.3,
        "length": 120,
        "top_diameter": 19,
        "top_height": 10,
        "top_adjacent_height": 3,
        "middle_diameter": 10,
        "middle_height": 94,
        "bottom_adjacent_height": 3,
        "bottom_diameter": 25,
        "bottom_height": 10,
        "radius": 30,
    },
    "DJ-20-140": {
        "type": "圆头吊钉",
        "factory": "现代营造",
        "name": "DJ-20-140",
        "abbreviation": "DJ",
        "capacity": 2.0,
        "length": 140,
        "top_diameter": 26,
        "top_height": 10,
        "top_adjacent_height": 3,
        "middle_diameter": 14,
        "middle_height": 114,
        "bottom_adjacent_height": 3,
        "bottom_diameter": 35,
        "bottom_height": 10,
        "radius": 37,
    },
    "DJ-25-170": {
        "type": "圆头吊钉",
        "factory": "现代营造",
        "name": "DJ-25-170",
        "abbreviation": "DJ",
        "capacity": 2.5,
        "length": 170,
        "top_diameter": 26,
        "top_height": 10,
        "top_adjacent_height": 3,
        "middle_diameter": 14,
        "middle_height": 144,
        "bottom_adjacent_height": 3,
        "bottom_diameter": 35,
        "bottom_height": 10,
        "radius": 37,
    },
    "DJ-30-210": {
        "type": "圆头吊钉",
        "factory": "现代营造",
        "name": "DJ-30-210",
        "abbreviation": "DJ",
        "capacity": 3.0,
        "length": 210,
        "top_diameter": 36,
        "top_height": 10,
        "top_adjacent_height": 3,
        "middle_diameter": 18,
        "middle_height": 184,
        "bottom_adjacent_height": 3,
        "bottom_diameter": 45,
        "bottom_height": 10,
        "radius": 47,
    },
    "DJ-50-240": {
        "type": "圆头吊钉",
        "factory": "现代营造",
        "name": "DJ-50-240",
        "abbreviation": "DJ",
        "capacity": 5.0,
        "length": 240,
        "top_diameter": 36,
        "top_height": 10,
        "top_adjacent_height": 3,
        "middle_diameter": 20,
        "middle_height": 214,
        "bottom_adjacent_height": 3,
        "bottom_diameter": 50,
        "bottom_height": 10,
        "radius": 47,
    },
    "DJ-75-300": {
        "type": "圆头吊钉",
        "factory": "现代营造",
        "name": "DJ-75-300",
        "abbreviation": "DJ",
        "capacity": 7.5,
        "length": 300,
        "top_diameter": 46,
        "top_height": 10,
        "top_adjacent_height": 3,
        "middle_diameter": 24,
        "middle_height": 274,
        "bottom_adjacent_height": 3,
        "bottom_diameter": 60,
        "bottom_height": 10,
        "radius": 59,
    },
}

ANCHOR = {
    "MS-6-60": {
        "type": "预埋锚栓",
        "factory": "现代营造",
        "name": "MS-6-60",
        "abbreviation": "MS",
        "capacity": 0.6,
        "m_diameter": 20,
        "m_length": 20,
        "anchor_name": "M6x1.0",
        "e_diameter": 6,
        "g": 16,
        "b": 5,
        "o_diameter": 10,
        "length": 40,
        "s_diameter": 4,
        "l_p": 40,
        "a": 6,
    },
    "MS-9-60": {
        "type": "预埋锚栓",
        "factory": "现代营造",
        "name": "MS-9-60",
        "abbreviation": "MS",
        "capacity": 0.9,
        "m_diameter": 22,
        "m_length": 20,
        "anchor_name": "M8x1.25",
        "e_diameter": 8,
        "g": 16,
        "b": 5,
        "o_diameter": 12,
        "length": 40,
        "s_diameter": 6,
        "l_p": 40,
        "a": 8,
    },
    "MS-12-70": {
        "type": "预埋锚栓",
        "factory": "现代营造",
        "name": "MS-12-70",
        "abbreviation": "MS",
        "capacity": 1.2,
        "m_diameter": 26,
        "m_length": 20,
        "anchor_name": "M10x1.5",
        "e_diameter": 10,
        "g": 22,
        "b": 5,
        "o_diameter": 16,
        "length": 50,
        "s_diameter": 8,
        "l_p": 50,
        "a": 9,
    },
    "MS-15-75": {
        "type": "预埋锚栓",
        "factory": "现代营造",
        "name": "MS-15-75",
        "abbreviation": "MS",
        "capacity": 1.5,
        "m_diameter": 28,
        "m_length": 20,
        "anchor_name": "M12x1.75",
        "e_diameter": 12,
        "g": 25,
        "b": 5,
        "o_diameter": 18,
        "length": 55,
        "s_diameter": 8,
        "l_p": 60,
        "a": 10,
    },
    "MS-24-80": {
        "type": "预埋锚栓",
        "factory": "现代营造",
        "name": "MS-24-80",
        "abbreviation": "MS",
        "capacity": 2.4,
        "m_diameter": 30,
        "m_length": 20,
        "anchor_name": "M14x2.0",
        "e_diameter": 14,
        "g": 28,
        "b": 5,
        "o_diameter": 20,
        "length": 60,
        "s_diameter": 10,
        "l_p": 100,
        "a": 11,
    },
    "MS-36-90": {
        "type": "预埋锚栓",
        "factory": "现代营造",
        "name": "MS-36-90",
        "abbreviation": "MS",
        "capacity": 3.6,
        "m_diameter": 32,
        "m_length": 20,
        "anchor_name": "M16x2.0",
        "e_diameter": 16,
        "g": 32,
        "b": 5,
        "o_diameter": 22,
        "length": 70,
        "s_diameter": 10,
        "l_p": 100,
        "a": 12,
    },
    "MS-60-115": {
        "type": "预埋锚栓",
        "factory": "现代营造",
        "name": "MS-60-115",
        "abbreviation": "MS",
        "capacity": 6.0,
        "m_diameter": 30,
        "m_length": 35,
        "anchor_name": "M20x2.5",
        "e_diameter": 20,
        "g": 38,
        "b": 5,
        "o_diameter": 25,
        "length": 80,
        "s_diameter": 12,
        "l_p": 100,
        "a": 12,
    },
    "MS-75-120": {
        "type": "预埋锚栓",
        "factory": "现代营造",
        "name": "MS-75-120",
        "abbreviation": "MS",
        "capacity": 7.5,
        "m_diameter": 42,
        "m_length": 20,
        "anchor_name": "M24x3.0",
        "e_diameter": 24,
        "g": 50,
        "b": 5,
        "o_diameter": 32,
        "length": 100,
        "s_diameter": 12,
        "l_p": 100,
        "a": 12,
    },
    "MS-120-172": {
        "type": "预埋锚栓",
        "factory": "现代营造",
        "name": "MS-120-172",
        "abbreviation": "MS",
        "capacity": 12.0,
        "m_diameter": 30,
        "m_length": 52,
        "anchor_name": "M30x3.5",
        "e_diameter": 30,
        "g": 60,
        "b": 5,
        "o_diameter": 42,
        "length": 120,
        "s_diameter": 22,
        "l_p": 120,
        "a": 12,
    },
}

# LIFT_HOOK = {
#     "WDG-6": {"type": "弯吊钩", "name": "WDG-6", "abbreviation": "WDG", "material": "HPB300", "diameter": 6,
#               "top_radius": 30, "top_height": 80, "bottom_radius": 20, "bottom_height": 300, "m_height": 40,
#               "a1": 80, "b1": 100, "a2": 40, "b2": 60, "d": 20},
#     "WDG-14": {"type": "弯吊钩", "name": "WDG-14", "abbreviation": "WDG", "material": "HPB300", "diameter": 14,
#                "top_radius": 40, "top_height": 30, "bottom_radius": 30, "bottom_height": 400, "m_height": 40,
#                "a1": 100, "b1": 120, "a2": 40, "b2": 60, "d": 20},
# }

RAILING = {
    "M1": {
        "name": "M1",
        "a": 90,
        "b": 90,
        "c": 20,
        "d": 100,
        "t": 6,
        "fi": 8,
        "depth": 15,
        "length": 5,
    },
    "M2": {
        "name": "M2",
        "a": 100,
        "b": 100,
        "c": 20,
        "d": 100,
        "t": 6,
        "fi": 8,
        "depth": 15,
        "length": 5,
    },
    "M3": {
        "name": "M3",
        "a": 100,
        "b": 100,
        "c": 20,
        "d": 120,
        "t": 6,
        "fi": 10,
        "depth": 15,
        "length": 5,
    },
    "M4": {
        "name": "M4",
        "a": 110,
        "b": 110,
        "c": 20,
        "d": 120,
        "t": 6,
        "fi": 10,
        "depth": 15,
        "length": 5,
    },
    "M5": {
        "name": "M5",
        "a": 120,
        "b": 120,
        "c": 25,
        "d": 140,
        "t": 8,
        "fi": 12,
        "depth": 15,
        "length": 5,
    },
    "M6": {
        "name": "M6",
        "a": 180,
        "b": 90,
        "c": 30,
        "d": 150,
        "t": 8,
        "fi": 12,
        "depth": 15,
        "length": 5,
    },
    "M7": {
        "name": "M7",
        "a": 240,
        "b": 90,
        "c": 30,
        "d": 150,
        "t": 6,
        "fi": 8,
        "depth": 15,
        "length": 5,
    },
}
